#!/usr/bin/env python3
"""Generate Keploy noise config from a review report.

Parses the "Dynamic Field Risks" section of a keploy review Markdown report
and generates a Keploy-compatible noise config YAML file.

Usage:
    python3 gen-noise-config.py --review-report reports/keploy-review.md --output keploy/config.yaml
    python3 gen-noise-config.py --review-report reports/keploy-review.md --output keploy/config.yaml --force
"""

import argparse
import os
import re
import sys
from pathlib import Path


# Mapping from detected dynamic field name -> list of Keploy noise paths
FIELD_TO_NOISE_PATHS = {
    "timestamp": [
        "resp.body.timestamp",
        "resp.header.Date",
        "resp.header.Expires",
    ],
    "created_at": ["resp.body.created_at", "resp.body.createdAt"],
    "updated_at": ["resp.body.updated_at", "resp.body.updatedAt"],
    "uuid": ["resp.header.X-Request-Id", "req.header.X-Request-Id"],
    "trace_id": ["resp.header.X-Trace-Id", "req.header.X-Trace-Id", "req.header.X-Request-Id"],
    "request_id": ["resp.header.X-Request-Id", "req.header.X-Request-Id"],
}

AUTO_GENERATED_HEADER = "# AUTO-GENERATED by gen-noise-config.py — REVIEW REQUIRED\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate Keploy noise config from review report dynamic fields"
    )
    parser.add_argument("--review-report", required=True, help="Path to Keploy review Markdown report")
    parser.add_argument("--output", required=True, help="Output Keploy config.yaml path")
    parser.add_argument("--force", action="store_true", help="Overwrite existing output file")
    return parser.parse_args()


def extract_dynamic_fields(report_path: str) -> list[str]:
    """Parse Section 7 (Dynamic Field Risks) from the review report and extract unique field names."""
    path = Path(report_path)
    if not path.exists():
        print(f"ERROR: Review report not found: {report_path}", file=sys.stderr)
        sys.exit(1)

    content = path.read_text(encoding="utf-8")

    # Look for Section 7: Dynamic Field Risks
    section_match = re.search(
        r"## 7\.\s*Dynamic Field Risks(.*?)(?=\n## |\Z)",
        content,
        re.DOTALL,
    )
    if not section_match:
        print("[NOISE] WARNING: Could not find '## 7. Dynamic Field Risks' section")
        return []

    section = section_match.group(1)

    if "No dynamic fields detected" in section:
        return []

    # Extract field names from table rows: | <field> | <file> | <line> |
    fields = set()
    for line in section.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        if line.lower().startswith("| field"):
            continue  # header row
        parts = [p.strip() for p in line.split("|")]
        # parts[0] is empty (before first |), parts[1] is field, ...
        if len(parts) >= 2 and parts[1] and parts[1] != "---":
            # Skip separator rows (|---|---|---|): all non-empty parts are dash-only
            if all(re.match(r"^-+$", p) for p in parts if p):
                continue
            # Field name must look like an identifier (letters, digits, underscores)
            field_name = parts[1]
            if re.match(r"^[a-zA-Z_][a-zA-Z0-9_]*$", field_name):
                fields.add(field_name)

    return sorted(fields)


def fields_to_noise_paths(fields: list[str]) -> list[str]:
    """Map field names to Keploy noise paths. Deduplicates and preserves order."""
    seen = set()
    paths = []
    for field in fields:
        mapped = FIELD_TO_NOISE_PATHS.get(field)
        if mapped:
            for p in mapped:
                if p not in seen:
                    seen.add(p)
                    paths.append(p)
        else:
            # Unknown field: default to resp.body.<field>
            default_path = f"resp.body.{field}"
            if default_path not in seen:
                seen.add(default_path)
                paths.append(default_path)
    return paths


def render_config_yaml(noise_paths: list[str]) -> str:
    """Render a Keploy config.yaml with the noise paths."""
    lines = [
        AUTO_GENERATED_HEADER,
        "#",
        "# This file configures which response fields should be ignored during Keploy test replay.",
        "# Fields listed here are dynamic (change between runs) and would cause false failures.",
        "#",
        "# Review each entry before using. Remove any that should be asserted.",
        "",
        "assertions:",
        "  noise:",
    ]
    for p in noise_paths:
        lines.append(f"    - {p}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    args = parse_args()

    fields = extract_dynamic_fields(args.review_report)
    print(f"[NOISE] Extracted {len(fields)} unique dynamic field(s): {fields}")

    if not fields:
        print("[NOISE] No dynamic fields found — no noise config needed.")
        sys.exit(0)

    noise_paths = fields_to_noise_paths(fields)
    print(f"[NOISE] Mapped to {len(noise_paths)} noise path(s)")

    output_path = Path(args.output)
    if output_path.exists() and not args.force:
        print(f"ERROR: Output file already exists: {output_path}", file=sys.stderr)
        print("Use --force to overwrite.", file=sys.stderr)
        sys.exit(1)

    output_dir = output_path.parent
    if output_dir != Path(".") and not output_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)

    yaml_content = render_config_yaml(noise_paths)
    output_path.write_text(yaml_content, encoding="utf-8")

    print(f"[NOISE] Wrote noise config: {output_path}")
    print(f"[NOISE] IMPORTANT: Review the file before using — paths are heuristic guesses.")


if __name__ == "__main__":
    main()
