# Keploy Asset Review Report - {{service_name}}

> Review Date: {{review_date}}
> Service: {{service_name}}
> Keploy Directory: {{keploy_dir}}

## 1. Coverage Summary

| Metric | Count |
|--------|-------|
| Total YAML files | {{total_files}} |
| Test cases | {{test_count}} |
| Mocks | {{mock_count}} |

## 2. HTTP Method Coverage

| Method | Count | Paths |
|--------|-------|-------|
{{method_coverage_table}}

## 3. Status Code Coverage

| Status Code | Count |
|-------------|-------|
{{status_code_table}}

## 4. Path Coverage

| Path | Methods |
|------|---------|
{{path_coverage_table}}

## 5. Sensitive Field Risks

{{sensitive_fields_section}}

## 6. Sensitive Data Pattern Risks

{{sensitive_data_section}}

## 7. Dynamic Field Risks

{{dynamic_fields_section}}

## 8. Archival Recommendation

{{archival_recommendation}}

---

*This report was generated by keploy-asset-reviewer. Review results are for reference only — human confirmation is required before archiving any baseline.*